In [159]:
import torch
print(torch.cuda.is_available())  # Should be True
print(torch.cuda.device_count())  # Number of GPUs
print(torch.cuda.get_device_name(0))  # Name of your GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

True
1
NVIDIA GeForce RTX 3060


In [160]:
scalar=torch.tensor(7)
scalar.ndim

0

In [161]:
vector=torch.tensor([7,7])
vector.ndim

1

In [162]:
matrix=torch.tensor([[[7,8],[5,7]],[[6,6],[6,8]]])
matrix.shape,matrix.ndim

(torch.Size([2, 2, 2]), 3)

In [163]:
random=torch.randn([4,5])
random

tensor([[-0.9594,  0.7205,  0.7398, -0.5046, -1.8604],
        [-0.5086,  0.4536,  0.2984,  0.3757, -0.5892],
        [ 1.3126, -1.2302, -0.5946,  0.3020, -0.4342],
        [-0.3792,  0.0972,  1.4934, -1.9816,  0.0779]])

In [164]:
zeros=torch.zeros(size=[3,3])
ones=torch.ones(size=[3,3])
print(zeros)
print(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [165]:
range=torch.arange(start=1,end=20,step=2)
range

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [166]:
newzeros=torch.zeros_like(zeros).dtype
newzeros

torch.float32

In [167]:
data=torch.tensor([[[3,4,5],[4,7,9]],[[1,2,1],[5,6,8]]])
data=data.to(device=device)
print(data)

tensor([[[3, 4, 5],
         [4, 7, 9]],

        [[1, 2, 1],
         [5, 6, 8]]], device='cuda:0')


In [168]:
data.device

device(type='cuda', index=0)

In [181]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [170]:
tensor*10

tensor([10, 20, 30])

In [171]:
tensor * tensor

tensor([1, 4, 9])

In [209]:
import torch


In [211]:

tensor=torch.tensor([1,2,3])
torch.matmul(tensor,tensor)


tensor(14)

In [231]:

tensor1=torch.tensor([[1,2],[2,3],[4,5]])
tensor2=torch.tensor([[1,2],[2,3],[4,5]])
tensor2=torch.transpose(tensor2,0,1)
torch.matmul(tensor1,tensor2)

tensor([[ 5,  8, 14],
        [ 8, 13, 23],
        [14, 23, 41]])

In [240]:
tensor=torch.tensor([1.0,2,3,3,4]).dtype
tensor

torch.float32

In [233]:
torch.max(tensor)

tensor(34)

In [236]:
torch.mean(tensor.type(torch.float32))

tensor(8.8000)

In [261]:
tensor1=torch.tensor([[1,2],[2,3],[4,5]],dtype=torch.float32)
tensor2=torch.tensor([[1,2],[2,3],[4,5]],dtype=torch.float64)
tensor1+tensor2

tensor([[ 2.,  4.],
        [ 4.,  6.],
        [ 8., 10.]], dtype=torch.float64)

In [6]:
import asyncio
from crawl4ai import AsyncWebCrawler

async def main():
    # Create an instance of AsyncWebCrawler
    async with AsyncWebCrawler() as crawler:
        # Run the crawler on a URL
        result = await crawler.arun(url="https://crawl4ai.com")

        # Print the extracted content
        print(result.markdown)

# Run the async main function
asyncio.run(main())

RuntimeError: asyncio.run() cannot be called from a running event loop

In [7]:
import kenlm

model = kenlm.Model('your_model.arpa')
sentence = "The quick brown fox jumps over the lazy dog"

print(model.score(sentence))  # log-probability


ModuleNotFoundError: No module named 'kenlm'

In [23]:
7323+1178



8501

In [2]:
import os
import requests
import time

# How many WET files to download (change as needed)
NUM_FILES =210

# Path to your local wet.paths file
paths_file = "/home/blu-bridge004/Desktop/pytorch/wet.paths(3)"

# Folder to save the WET files
output_dir = '/media/blu-bridge004/Expansion/train/wet_files_200_500'
os.makedirs(output_dir, exist_ok=True)

# Read first N paths from wet.paths
with open(paths_file, 'r') as f:
    lines = [line.strip() for line in f.readlines()[290:500]]

# Download each WET file
base_url = "https://data.commoncrawl.org/"

for i, path in enumerate(lines):
    a=time.time()
    url = base_url + path
    filename = os.path.join(output_dir, os.path.basename(path))

    print(f"[{i+1}/{NUM_FILES}] Downloading: {url}")
    response = requests.get(url, stream=True)

    if response.status_code == 200:
        with open(filename, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)
        print(f"Saved to: {filename} ")
        b = time.time()
        print(f"total time taken  : {b-a}s")
    else:
        print(f"Failed to download {url}, status code {response.status_code}")

[1/210] Downloading: https://data.commoncrawl.org/crawl-data/CC-MAIN-2025-13/segments/1742004432822.9/wet/CC-MAIN-20250315031626-20250315061626-00290.warc.wet.gz
Saved to: /media/blu-bridge004/Expansion/train/wet_files_200_500/CC-MAIN-20250315031626-20250315061626-00290.warc.wet.gz 
total time taken  : 6.0397047996521s
[2/210] Downloading: https://data.commoncrawl.org/crawl-data/CC-MAIN-2025-13/segments/1742004432822.9/wet/CC-MAIN-20250315031626-20250315061626-00291.warc.wet.gz
Saved to: /media/blu-bridge004/Expansion/train/wet_files_200_500/CC-MAIN-20250315031626-20250315061626-00291.warc.wet.gz 
total time taken  : 13.911158323287964s
[3/210] Downloading: https://data.commoncrawl.org/crawl-data/CC-MAIN-2025-13/segments/1742004432822.9/wet/CC-MAIN-20250315031626-20250315061626-00292.warc.wet.gz
Saved to: /media/blu-bridge004/Expansion/train/wet_files_200_500/CC-MAIN-20250315031626-20250315061626-00292.warc.wet.gz 
total time taken  : 5.522820472717285s
[4/210] Downloading: https://dat